---
- name: Playbook start job in Nomad
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Create Job Manifest
    template:
      src:  backend-service.hcl.j2
      dest: backend-service.hcl

  - name: Start Job
    shell:
      chdir: /mnt
      cmd: "/usr/bin/levant deploy backend-service.hcl"
    environment:
        NOMAD_ADDR: "{{ nomad_url }}"